config/routes.rb
Rails.application.routes.draw do

  root to: "todo_lists#index"
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts

  resources :sessions, only: [:create, :destroy, :new]

  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  #has_and_belongs_to_many :tags

  default_scope { order due_date: :asc }
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  #before_action :set_todo_item


  # GET /todo_items
  # GET /todo_items.json

  def index
    @todo_items = TodoItem.all
    #@todo_items = TodoItem.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
    @todo_item= @todo_list.todo_items.find(params[:id])
  end

  # GET /todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_items/1/edit
  def edit
    @todo_item= @todo_list.todo_items.find(params[:id])
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }

      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    @todo_item= @todo_list.todo_items.find(params[:id])
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item=@todo_list.todo_items.find(params[:id])
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
    #@todo_item=@todo_list.todo_items.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_todo_item
    @todo_item= @todo_list.todo_items.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_item_params
    params.require(:todo_item).permit(:task_title, :due_date, :description, :done)
  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item]) do |f| %>
    <% if @todo_item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

          <ul>
            <% @todo_item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :due_date %><br>
      <%= f.text_field :due_date, :class => 'datepicker' %>
    </div>
    <p></p>
    <div class="field">
      <%= f.label :task_title %><br>
      <%= f.text_field :task_title %>
    </div>
    <p></p>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <p></p>
    <div class="field">
      <%= f.label :done %><br>
      <%= f.check_box :done %>
    </div>
    <p></p>
    <div class="actions">
      <%= f.submit %>
    </div>
    <p></p>
<% end %>

app/views/todo_items/_formNew.html.erb
<%= form_for([@todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= f.label :due_date %><br>
      <%= f.text_field :due_date, :class => 'datepicker' %>
    </div>
    <p></p>
    <div class="field">
    <%= f.label :task_title %><br>
    <%= f.text_field :task_title %>
  </div>
    <p></p>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <p></p>
    <p></p>
  <div class="actions">
    <%= f.submit %>
  </div>
    <p></p>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_list, @todo_item] %> |
<%= link_to 'Back', @todo_list %>

app/views/todo_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Items</h1>

<table>
  <thead>
  <tr>
    <th>Task title</th>
    <th>Due date</th>
    <th>Description</th>
    <th>Done</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.task_title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.done %></td>
        <td><%= link_to 'Show', todo_item %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
        <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'formNew' %>

<%= link_to 'Back', @todo_list %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Task Title:</strong>
  <%= @todo_item.task_title %>
</h1>

<h4>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</h4>

<p>
  <strong>Done yet?</strong>
  <%= @todo_item.done %>
</p>
<p>
  <strong>Description:</strong>
</p>
<h3>
  <%= @todo_item.description %>
</h3>
<h1></h1>

<%= link_to 'Edit Todo Item', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Delete Todo Item', [@todo_list, @todo_item], method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to Todo List', @todo_list %>