config/routes.rb
Rails.application.routes.draw do

  root to: "todo_lists#index"
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts

  resources :sessions, only: [:create, :destroy, :new]

  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items
  has_many :my_todo_items

  default_scope { order list_due_date: :asc }
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    #@todo_lists = TodoList.all
    @todo_lists = TodoList.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_items = @todo_list.todo_items.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }

      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_list_params
    params.require(:todo_list).permit(:list_due_date, :list_name)
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
  def all_done?(todo_list)
    return true if todo_list.todo_items.empty?
    todo_list.todo_items.all?(&:done)
  end

  def due_date_overall_class(todo_list)
    all_done?(todo_list) ? 'task_done' : 'task_not_done'
  end

  def update_attributes(attributes)
    self.attributes = attributes
    save
  end

end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
    <% if @todo_list.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

          <ul>
            <% @todo_list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :list_due_date %><br>
      <%= f.text_field :list_due_date, :class => 'datepicker' %>
    </div>
    <p></p>
    <div class="field">
      <%= f.label :list_name %><br>
      <%= f.text_field :list_name %>
    </div>
    <p></p>
    <div class="actions">
      <%= f.submit %>
    </div>
    <p></p>

<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<body>
<h1>Todo Lists</h1>
<p>
</p>
<%= link_to 'New Todo list', new_todo_list_path %>
<p></p>
<table>
  <thead>
  <tr>
    <th>List Due Date</th>
    <th>List Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @todo_lists.each do |todo_list| %>
      <tr>
        <td> <span class=" <%= all_done?(todo_list)?  'task_done': 'task_not_done' %> ">  <%= todo_list.list_due_date %> </span></td>
        <td><%= link_to todo_list.list_name, todo_list %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<p />
<%= will_paginate @todo_lists %>
<br>
</body>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h1>
  <strong>List Name:</strong>
  <%= @todo_list.list_name %>
</h1>

<h4>
  <strong>List Due Date:</strong>
  <%= @todo_list.list_due_date %>
</h4>
<P></P>

<table>
  <thead>
  <tr>
    <th>Due Date</th>
    <th>Task Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <%= link_to 'Add Todo item', new_todo_list_todo_item_path(@todo_list) %>
  <p></p>
  <tbody>
  <% @todo_items.each do |todo_item| %>
      <tr>
        <td><span class=" <%= todo_item.done ? 'task_done': 'task_not_done' %> "> <%= todo_item.due_date %> </span> </td>
        <td><%= link_to todo_item.task_title, [@todo_list, todo_item] %></td>

        <td ><span class=" <%= todo_item.done ? 'display_done': 'display_not_done' %> ">
          <%= form_for([@todo_list, todo_item], method: :put, id: "test") do |f| %>
              <%= f.hidden_field :done, value: '1' %>
              <%= f.submit 'Mark Item Done' -%>
          <% end %>
            </span>
        </td>

      </tr>
  <% end %>
  </tbody>
</table>

<p />
<%= will_paginate  @todo_items %>
<br>

<%= link_to 'Edit Todo List', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Delete Todo List', @todo_list, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to Todo Lists', todo_lists_path %>