config/routes.rb
Rails.application.routes.draw do

  root to: "todo_lists#index"
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts

  resources :sessions, only: [:create, :destroy, :new]

  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user

  validates :age, :inclusion => 20..100
  validate :gender_entries

  def gender_entries
    if (gender != "male") && (gender != "female") && (gender != "N/A")
      errors.add(:gender, " is not specified as male, female or N/A")
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @account = current_user.account
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = current_user.account
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    @account = current_user.account
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update

    puts "\n\nFrom Account_Controller Update method: " + params.to_s

    puts "Current @account: " => @account.as_json

    puts "Current @account id: " => @account.id
    puts "params[:id] is: " => params[:id]

    #@account = current_user.account.find(params[:id])
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:first_name, :last_name, :age, :gender)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
    <% if @account.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

          <ul>
            <% @account.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :gender %><br>
      <%= f.text_field :gender %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Account Info</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @account.first_name %></td>
    <td><%= @account.last_name %></td>
    <td><%= @account.age %></td>
    <td><%= @account.gender %></td>
    <td></td>
  </tr>
  </tbody>
</table>



<br>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1>Updated Account Information</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @account.first_name %></td>
    <td><%= @account.last_name %></td>
    <td><%= @account.age %></td>
    <td><%= @account.gender %></td>
  </tr>
  </tbody>
</table>

<br>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', todo_lists_path %>